version: '3.8'  # Especifica a versão do Docker Compose

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    container_name: impulse_api_flask
